# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import matches_pb2 as matches__pb2


class CareerMatchesServiceStub(object):
  """Interface exposed by the service.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetMatches = channel.unary_unary(
        '/CareerMatchesService/GetMatches',
        request_serializer=matches__pb2.CareerMatchesRequest.SerializeToString,
        response_deserializer=matches__pb2.CareerMatchesResponse.FromString,
        )


class CareerMatchesServiceServicer(object):
  """Interface exposed by the service.
  """

  def GetMatches(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CareerMatchesServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetMatches': grpc.unary_unary_rpc_method_handler(
          servicer.GetMatches,
          request_deserializer=matches__pb2.CareerMatchesRequest.FromString,
          response_serializer=matches__pb2.CareerMatchesResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CareerMatchesService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
